### ISSUE TITLE
示例panic

### ISSUE THREAD

**Issue by liuhengloveyou** [ipipdotnet/datx-go#1]
`$ go run geo.go 
[LEVEL3.COM 骨干网 LEVEL3.COM 骨干网  ] <nil>
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/ipipdotnet/datx-go.(*District).Find(0xc420060100, 0x10d9387, 0xd, 0x34, 0x0, 0x0, 0x0, 0x0)
	/Users/liuheng/go/src/github.com/ipipdotnet/datx-go/district.go:92 +0x399
main.main()
	/Users/liuheng/go/src/github.com/liuhengloveyou/HTTPDNS/geo.go:18 +0x16c
exit status 2
`

**Comment by ipipdotnet** [comment]
你肯定使用错方法了
