### ISSUE TITLE
您好， 可以支持远程IP文件的加载吗？

### ISSUE THREAD

**Issue by deancn** [ipipdotnet/datx-go#4]
当前 city.go 中load function是加载文件的， 支持一下远程文件吧？

或是aws s3读取文件。

**Comment by ipipdotnet** [comment]
@deanchina 如果支持远程URL，就需要对下载成功后的数据文件做效检，以确保文件的完整性，还要考虑数据文件的reload，这个需求可以独立出一个模块来做。
